##配置服务器启动端口号
server:
  port: 8080
  #session过期时间  3600秒
  servlet:
    session:
      timeout:  
           3600
 
 

##配置数据库连接
spring:
  datasource:
          name: blog
          url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=utf-8
          username: root
          password: 
          # 使用druid数据源
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          
           #数据库参数配置
           #初始化数量
          initialSize: 1
          #最小连接
          minIdle: 1
          #最大活跃数
          maxActive: 20
          #最大连接等待超时时间
          maxWait: 60000
          #打开PSCache，并且指定每个连接PSCache的大小
          poolPreparedStatements: true
          maxPoolPreparedStatementPerConnectionSize: 20
          #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
          connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
         # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
          timeBetweenEvictionRunsMillis: 60000
          # 配置一个连接在池中最小生存的时间，单位是毫秒
          minEvictableIdleTimeMillis: 300000
          
          # 校验SQL，Oracle配置 spring.datasource.validationQuery=SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
          validationQuery: select 1 from dual
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
          filters: stat, wall, log4j
          # 合并多个DruidDataSource的监控数据
          useGlobalDataSourceStat: true

#日志配置 显示sql
logging:
  level:
    root: info
    com.frame: debug
    ##com.frame: INFO
    org.springframework.session: debug
    org.springframework.cache: debug
  ##指定日志配置文件路径 默认的话需要房子 根目录下
  config: classpath:config/log4j2.xml
    
##配置mybatis 扫描包 mapping 下任何文件都被扫描到
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  #type-aliases-package: com.frame.blog.model  
  #myatbis配置文件
  config-location: classpath:config/mybatis-conf.xml


###配置  actuator 对应一些 ENDPOINTS配置  
management:
  server:
   port: 8084
   servlet:
     context-path: /framework-admin # 只有在设置了 management.server.port 时才有效 
  ## 配置根目录 省略  /actuator 层路径 
  endpoints:
    web:
      base-path: /
       
  ##配置 mapping 映射路径对外显示 为false 不显示为 true
  endpoint:
    mappings:
      enabled: true
   
  
   
###配置info节点  actuator
info:
  author:
    name: framework-admin
    email: 1154698609@qq.com
  baseinfo:
    age: 26
    hobbies: running
  build:
    artifact: "@project.artifactId@"
    name: "@project.name@"
    version: "@project.version@"




